objective:
  Linear Regression:
    device: "cuda"

dataset:
  simulated:
    n: [30384]
    d1: [4000]
    d2: [4000]
    iid: ["true"]
    n_blocks: [16]
    noise: [0.1]

solver:
  all-reduce:
    batch_size: [64, 512, 2048]
    lr: [1e-3]

parallel_config: config_parallel.yml
n_repetitions: 1
timeout: 200