objective:
  all-reduce:
    device: "cuda"

dataset:
  nanogpt:
    n_chunks: 4

solver:
  all-reduce:
    local_batch_size: [16]
    lr: [1e-3]
    slurm_nodes: [2,4,8,16]
    slurm_gpus_per_node: [1]
  all-reduce-nolock:
    local_batch_size: [16]
    lr: [1e-3]
    slurm_nodes: [2,4,8,16]
    slurm_gpus_per_node: [1]
  ddp:
    local_batch_size: [16]
    lr: [1e-3]
    slurm_nodes: [2,4,8,16]
    slurm_gpus_per_node: [1]

parallel_config: config_parallel_nanogpt.yml
n_repetitions: 1
timeout: 100000