objective:
  all-reduce:
    device: "cuda"

dataset:
  mlp:
    d: [2000, 4000]
    layers: [1, 4]

solver:
  all-reduce:
    local_batch_size: 10000
    lr: [1e-3]
    slurm_nodes: [1, 2, 4, 8]
  all-reduce-nolock:
    local_batch_size: 10000
    lr: [1e-3]
    slurm_nodes: [1, 2, 4, 8]
  ddp:
    local_batch_size: 10000
    lr: [1e-3]
    slurm_nodes: [1, 2, 4, 8]

parallel_config: config_parallel.yml
n_repetitions: 5
timeout: 100000