objective:
  Linear Regression:
    device: "cuda"

dataset:
  simulated:
    n: [30384]
    d1: [4000]
    d2: [4000]

solver:
  all-reduce:
    batch_size: [64, 512, 2048]
    lr: [1e-3]
    slurm_nodes: [4]
    slurm_gpus_per_node: [1]

parallel_config: config_parallel.yml
n_repetitions: 1
timeout: 200