objective:
  Linear Regression:
    device: "cuda"

dataset:
  simulated:
    n: [32768]
    d1: [4000]

solver:
  all-reduce:
    batch_size: [4096]
    lr: [1e-3]
    slurm_nodes: [2]
    slurm_gpus_per_node: [1]
  ddp:
    batch_size: [4096]
    lr: [1e-3]
    slurm_nodes: [2]
    slurm_gpus_per_node: [1]

parallel_config: config_parallel.yml
n_repetitions: 5
timeout: 100000